### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [TeamNewPipe/NewPipe-legacy#56] opened 2020-12-27 08:16 UTC
### Checklist

- [y] I am using the latest version - x.xx.x 
- [y] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo. 
- [y] I have read the contribution guidelines given at https://github.com/TeamNewPipe/NewPipe/blob/HEAD/.github/CONTRIBUTING.md.
- [y] This issue contains only one bug. I will open one issue for every bug report I want to file.

### Steps to reproduce the bug

1. Go to first page
2. See the bug

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the first page, the text in the red box overlap with each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
Because of some problems with my eyesight, I often use the largest font and display.
![297165ECE247F4EDC808C49B7E0633F7](https://user-images.githubusercontent.com/18572115/103166639-1ec12700-485f-11eb-8b4a-f550f2a36e7f.png)
App version is 0.20.2, my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="443" alt="bug-newpipelegacy" src="https://user-images.githubusercontent.com/18572115/103166603-bb36f980-485e-11eb-9616-aee1ec3131b7.png">

### Actual behaviour

use the largest **_font_** and **_display_**.

### Expected behavior

Hope to solve the problem of overlap.

### Screenshots/Screen recordings

<img width="443" alt="bug-newpipelegacy" src="https://user-images.githubusercontent.com/18572115/103166613-db66b880-485e-11eb-979f-51cf23837e8b.png">

### Device info

 - Android version/Custom ROM version: Android 8.0
 - Device model: Google nexus 6

**Comment by friendlyanon** [comment] 2020-12-27 11:37
Nexus 6 never came with Android older than API 21. If you are using the legacy version, then stop doing that and use the upstream version. If the issue persists, let us know.

@TobiGr I can't transfer the issue. Can you please transfer to upstream?

**Comment by B0pol** [comment] 2020-12-27 12:01
You can close it, it is a duplicate of 
https://github.com/TeamNewPipe/NewPipe/issues/5289, https://github.com/TeamNewPipe/NewPipe/issues/5096

**Closed** 2020-12-27 12:09 UTC
Labels: bug

**Comment by franklinbill** [comment] 2020-12-30 09:14
Thanks for your reply!
