### ISSUE TITLE
Background Player Doesn't Play more that 2 videos.

### ISSUE THREAD

**Issue by RuthlessRuler** [TeamNewPipe/NewPipe-legacy#6] opened 2019-03-13 15:16 UTC
When More than 2 Videos are enqued as Background playback, The video after the second one doesn't play and is stuck at loading.

**Comment by friendlyanon** [comment] 2019-06-12 16:52
Can't reproduce, closing for now.

**Closed by friendlyanon** 2019-06-12 16:52 UTC
