### ISSUE TITLE
App Crashes when started without Network Access

### ISSUE THREAD

**Issue by RuthlessRuler** [TeamNewPipe/NewPipe-legacy#5] opened 2019-03-13 15:14 UTC
As the title suggest the app crashes when the app is started without Internet Access.

**Comment by nift4** [comment] 2019-03-15 20:23
I'm not from the NewPipe Team, but a crash report is useful.

**Comment by friendlyanon** [comment] 2019-06-12 16:50
Doesn't crash for me, can't reproduce. Closing for now.

**Closed by friendlyanon** 2019-06-12 16:50 UTC
